DS-311: configurable port numbers
cyverse/ds-playbooks pull request #14
Opened 2021-03-12 19:53 UTC by ianmcorvidae

Allows configuring the AMQP and the management ports using the rabbitmq configuration file.

2021-03-15 18:35 UTC, tedgin requested changes
Would you mind switching the `_rabbitmq_port` and `_rabbitmq_management_port` variable definitions to the `_var: "{{ var | default(<default value>) }}"` form? It expresses the intent more clearly.

Other than that, it looks good.

2021-03-16 18:05 UTC, ianmcorvidae commented
That's a good idea, I'll make that change.

2021-03-16 18:07 UTC, ianmcorvidae commented
@tedgin the change is made!

2021-03-17 18:29 UTC, tedgin approved these changes

2021-03-17 18:29 UTC, merged