logging when environment bringup fails
cyverse/ds-playbooks pull request #41
Opened 2022-09-19 18:52 UTC by Urvika-gola

When environment bringup fails - log the failure, print the output that contains 'play-recap' and return 1.

2022-09-23 19:13 UTC, tedgin requested changes

2022-09-23 19:13 UTC, tedgin commented on testing/ansible-tester/test-playbook.sh
> -	printf 'waiting for environment to be ready\n'
It's import to let the user know that they are waiting for the environment to be ready, so please don't delete this line.

2022-09-23 19:13 UTC, tedgin commented on testing/ansible-tester/test-playbook.sh
> +		return 1
Please follow  the Data Store's Bash coding standards.

2022-09-27 06:00 UTC, Urvika-gola commented
@tedgin, I have addressed the review comments as you suggested.

2022-10-05 18:47 UTC, closed without merging